/**
 * VersionHistoryPanel 单元测试
 *
 * 测试范围：
 *   - 无章节状态：渲染"请先选择一个章节"
 *   - 空版本状态：渲染"暂无历史版本" + "点击上方保存按钮创建快照"
 *   - 保存对话框：打开 / 输入备注 / 保存 → saveVersion
 *   - 保存对话框：取消 → 不调用 saveVersion
 *   - Enter 键触发保存
 *   - 版本列表渲染：当前版本 + 历史版本 (n)
 *   - 点击版本进入 diff 视图
 *   - 关闭按钮：仅在 onClose 传入时渲染
 *   - 删除版本 + confirm
 *   - 恢复版本 + confirm → restoreVersion + bumpContentEpoch
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, cleanup, waitFor } from '@testing-library/react';
import '@testing-library/jest-dom/vitest';
// confirm 已替换为基于 Zustand 的异步 confirm，统一 mock @/hooks/useConfirm
vi.mock('@/hooks/useConfirm', () => ({ confirm: vi.fn(), ConfirmDialog: () => null }));
import { confirm } from '@/hooks/useConfirm';
const confirmMock = vi.mocked(confirm);
import VersionHistoryPanel from '@/components/editor/VersionHistoryPanel';
import { useAppStore } from '@/store/useAppStore';
import type { Chapter, ChapterVersion } from '@/types';

// ============ 测试 fixtures ============
function makeChapter(overrides: Partial<Chapter> = {}): Chapter {
  return {
    id: 'ch-1',
    projectId: 'p1',
    parentId: null,
    title: '第一章',
    summary: '摘要',
    order: 0,
    level: 2,
    levelType: 'chapter',
    status: 'draft',
    wordCount: 100,
    content: '<p>当前正文</p>',
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
    ...overrides,
  };
}

function makeVersion(overrides: Partial<ChapterVersion> = {}): ChapterVersion {
  return {
    id: 'ver-1',
    chapterId: 'ch-1',
    version: 1,
    content: '<p>旧版本正文</p>',
    wordCount: 80,
    snapshotTime: '2024-01-01T10:00:00.000Z',
    description: '测试版本',
    autoGenerated: false,
    ...overrides,
  };
}

// ============ store mock 辅助 ============
// 注意：store 中 versions 为 Record<chapterId, ChapterVersion[]>，
// 测试用例以数组形式传入 versions，此处按 currentChapterId 自动包装成 map。
function mockStore(overrides: Partial<{
  currentChapterId: string | null;
  chapters: Chapter[];
  versions: ChapterVersion[];
  saveVersion: ReturnType<typeof vi.fn>;
  restoreVersion: ReturnType<typeof vi.fn>;
  updateChapterContent: ReturnType<typeof vi.fn>;
  bumpContentEpoch: ReturnType<typeof vi.fn>;
  deleteVersion: ReturnType<typeof vi.fn>;
  setPendingScrollTo: ReturnType<typeof vi.fn>;
}> = {}) {
  const saveVersion = overrides.saveVersion || vi.fn();
  const restoreVersion = overrides.restoreVersion || vi.fn();
  const updateChapterContent = overrides.updateChapterContent || vi.fn();
  const bumpContentEpoch = overrides.bumpContentEpoch || vi.fn();
  const deleteVersion = overrides.deleteVersion || vi.fn();
  const setPendingScrollTo = overrides.setPendingScrollTo || vi.fn();

  const currentChapterId = overrides.currentChapterId ?? null;
  const versionsMap: Record<string, ChapterVersion[]> = {};
  if (currentChapterId && overrides.versions) {
    versionsMap[currentChapterId] = overrides.versions;
  }

  useAppStore.setState({
    currentChapterId,
    chapters: overrides.chapters ?? [],
    versions: versionsMap,
    saveVersion,
    restoreVersion,
    updateChapterContent,
    bumpContentEpoch,
    deleteVersion,
    setPendingScrollTo,
  });

  return { saveVersion, restoreVersion, updateChapterContent, bumpContentEpoch, deleteVersion, setPendingScrollTo };
}

describe('VersionHistoryPanel', () => {
  let originalAlert: typeof window.alert;
  let alertMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    originalAlert = window.alert;
    alertMock = vi.fn();
    confirmMock.mockReset();
    confirmMock.mockResolvedValue(true);
    window.alert = alertMock as never;
    vi.useFakeTimers({ shouldAdvanceTime: true });
  });

  afterEach(() => {
    window.alert = originalAlert;
    vi.useRealTimers();
    cleanup();
  });

  // ============ 无章节状态 ============
  describe('无章节状态', () => {
    it('currentChapterId 为 null 时渲染"请先选择一个章节"', () => {
      mockStore({ currentChapterId: null, chapters: [] });
      render(<VersionHistoryPanel />);
      expect(screen.getByText('请先选择一个章节')).toBeInTheDocument();
    });

    it('currentChapterId 不在 chapters 中时也渲染"请先选择一个章节"', () => {
      mockStore({ currentChapterId: 'non-existent', chapters: [makeChapter({ id: 'ch-1' })] });
      render(<VersionHistoryPanel />);
      expect(screen.getByText('请先选择一个章节')).toBeInTheDocument();
    });
  });

  // ============ 空版本状态 ============
  describe('空版本状态', () => {
    it('有章节但无版本时渲染"暂无历史版本"', () => {
      const chapter = makeChapter();
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      render(<VersionHistoryPanel />);
      expect(screen.getByText('暂无历史版本')).toBeInTheDocument();
      expect(screen.getByText('点击上方保存按钮创建快照')).toBeInTheDocument();
    });

    it('标题"版本历史"始终渲染（有章节时）', () => {
      const chapter = makeChapter();
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      render(<VersionHistoryPanel />);
      expect(screen.getByText('版本历史')).toBeInTheDocument();
    });
  });

  // ============ 保存对话框 ============
  describe('保存对话框', () => {
    it('点击保存按钮打开对话框', () => {
      const chapter = makeChapter();
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      render(<VersionHistoryPanel />);
      // 点击"保存当前版本"按钮（title 属性）
      const saveBtn = screen.getByTitle('保存当前版本');
      fireEvent.click(saveBtn);
      // 对话框出现，含"版本备注（可选）..."placeholder
      expect(screen.getByPlaceholderText('版本备注（可选）...')).toBeInTheDocument();
      expect(screen.getByText('保存')).toBeInTheDocument();
      expect(screen.getByText('取消')).toBeInTheDocument();
    });

    it('输入备注后点击"保存"调用 saveVersion 并关闭对话框', () => {
      const chapter = makeChapter();
      const { saveVersion } = mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByTitle('保存当前版本'));
      const input = screen.getByPlaceholderText('版本备注（可选）...');
      fireEvent.change(input, { target: { value: '我的备注' } });
      fireEvent.click(screen.getByText('保存'));
      expect(saveVersion).toHaveBeenCalledWith('ch-1', '我的备注');
      // 对话框关闭
      expect(screen.queryByPlaceholderText('版本备注（可选）...')).not.toBeInTheDocument();
    });

    it('点击"取消"不调用 saveVersion 并关闭对话框', () => {
      const chapter = makeChapter();
      const { saveVersion } = mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByTitle('保存当前版本'));
      fireEvent.click(screen.getByText('取消'));
      expect(saveVersion).not.toHaveBeenCalled();
      expect(screen.queryByPlaceholderText('版本备注（可选）...')).not.toBeInTheDocument();
    });

    it('Enter 键触发保存', () => {
      const chapter = makeChapter();
      const { saveVersion } = mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByTitle('保存当前版本'));
      const input = screen.getByPlaceholderText('版本备注（可选）...');
      fireEvent.change(input, { target: { value: '回车保存' } });
      fireEvent.keyDown(input, { key: 'Enter' });
      expect(saveVersion).toHaveBeenCalledWith('ch-1', '回车保存');
    });

    it('空备注时 saveVersion 收到 undefined', () => {
      const chapter = makeChapter();
      const { saveVersion } = mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByTitle('保存当前版本'));
      fireEvent.click(screen.getByText('保存'));
      // versionName 为空字符串，handleSaveVersion 用 `versionName || undefined`
      expect(saveVersion).toHaveBeenCalledWith('ch-1', undefined);
    });
  });

  // ============ 版本列表渲染 ============
  describe('版本列表渲染', () => {
    it('渲染"当前版本"卡片与"历史版本 (n)"标题', () => {
      const chapter = makeChapter({ wordCount: 500 });
      const versions = [
        makeVersion({ id: 'v1', version: 1, description: '第一版' }),
        makeVersion({ id: 'v2', version: 2, description: '第二版' }),
      ];
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      render(<VersionHistoryPanel />);
      expect(screen.getByText('当前版本')).toBeInTheDocument();
      expect(screen.getByText(/历史版本/)).toBeInTheDocument();
      expect(screen.getByText('第一版')).toBeInTheDocument();
      expect(screen.getByText('第二版')).toBeInTheDocument();
    });

    it('版本无 description 时显示"版本 N"', () => {
      const chapter = makeChapter();
      const versions = [makeVersion({ id: 'v1', version: 3, description: undefined })];
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      render(<VersionHistoryPanel />);
      expect(screen.getByText('版本 3')).toBeInTheDocument();
    });
  });

  // ============ 点击版本进入 diff 视图 ============
  describe('点击版本进入 diff 视图', () => {
    it('点击版本后进入 diff 视图，显示"旧版本"/"当前版本"列标题', async () => {
      const chapter = makeChapter({ content: '<p>当前正文</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>旧正文</p>' })];
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByText('测试版本'));
      // 等待 setTimeout(30) 计算完成
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('旧版本')).toBeInTheDocument();
        expect(screen.getByText('当前版本')).toBeInTheDocument();
      });
    });

    it('点击版本后显示"恢复此版本"按钮', async () => {
      const chapter = makeChapter({ content: '<p>当前正文</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>旧正文</p>' })];
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByText('测试版本'));
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('恢复此版本')).toBeInTheDocument();
      });
    });
  });

  // ============ 关闭按钮 ============
  describe('关闭按钮', () => {
    it('未传入 onClose 时不渲染关闭按钮', () => {
      const chapter = makeChapter();
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      const { container } = render(<VersionHistoryPanel />);
      // header 中只有"保存当前版本"按钮，无 X 关闭按钮
      // 通过查找 header 区域的 button 数量判断
      const headerButtons = container.querySelectorAll('button[title], button:not([title])');
      // 仅"保存当前版本"按钮（有 title），无额外关闭按钮
      const closeBtns = Array.from(headerButtons).filter(b => !b.getAttribute('title'));
      expect(closeBtns.length).toBe(0);
    });

    it('传入 onClose 时渲染关闭按钮并触发回调', () => {
      const chapter = makeChapter();
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions: [] });
      const onClose = vi.fn();
      render(<VersionHistoryPanel onClose={onClose} />);
      // 找到关闭按钮：header 中除"保存当前版本"外的 button
      // 通过 X 图标难以定位，用 getAllByRole + 过滤
      const headerButtons = screen.getAllByRole('button');
      // 找到无 title 的按钮（关闭按钮无 title，保存按钮有 title="保存当前版本"）
      const closeBtn = headerButtons.find(b => !b.getAttribute('title'));
      expect(closeBtn).toBeDefined();
      fireEvent.click(closeBtn!);
      expect(onClose).toHaveBeenCalledTimes(1);
    });
  });

  // ============ 删除版本 ============
  describe('删除版本', () => {
    it('点击删除 + confirm true 调用 deleteVersion', async () => {
      const chapter = makeChapter();
      const versions = [makeVersion({ id: 'v1', description: '删除测试' })];
      const { deleteVersion } = mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      confirmMock.mockResolvedValue(true);
      render(<VersionHistoryPanel />);
      // 找到删除按钮（title="删除此版本"）
      const deleteBtn = screen.getByTitle('删除此版本');
      fireEvent.click(deleteBtn);
      expect(confirmMock).toHaveBeenCalled();
      await waitFor(() => expect(deleteVersion).toHaveBeenCalledWith('ch-1', 'v1'));
    });

    it('confirm false 时不调用 deleteVersion', () => {
      const chapter = makeChapter();
      const versions = [makeVersion({ id: 'v1', description: '删除测试' })];
      const { deleteVersion } = mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      confirmMock.mockResolvedValue(false);
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByTitle('删除此版本'));
      expect(deleteVersion).not.toHaveBeenCalled();
    });
  });

  // ============ 恢复版本 ============
  describe('恢复版本', () => {
    it('点击"恢复此版本" + confirm true 调用 restoreVersion + bumpContentEpoch', async () => {
      const chapter = makeChapter({ content: '<p>当前正文</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>旧正文</p>' })];
      const { restoreVersion, bumpContentEpoch } = mockStore({
        currentChapterId: 'ch-1',
        chapters: [chapter],
        versions,
      });
      confirmMock.mockResolvedValue(true);
      render(<VersionHistoryPanel />);
      // 进入 diff 视图
      fireEvent.click(screen.getByText('测试版本'));
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('恢复此版本')).toBeInTheDocument();
      });
      fireEvent.click(screen.getByText('恢复此版本'));
      expect(confirmMock).toHaveBeenCalled();
      await waitFor(() => expect(restoreVersion).toHaveBeenCalledWith('ch-1', 'v1'));
      expect(bumpContentEpoch).toHaveBeenCalled();
    });

    it('confirm false 时不调用 restoreVersion', async () => {
      const chapter = makeChapter({ content: '<p>当前正文</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>旧正文</p>' })];
      const { restoreVersion } = mockStore({
        currentChapterId: 'ch-1',
        chapters: [chapter],
        versions,
      });
      confirmMock.mockResolvedValue(false);
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByText('测试版本'));
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('恢复此版本')).toBeInTheDocument();
      });
      fireEvent.click(screen.getByText('恢复此版本'));
      expect(restoreVersion).not.toHaveBeenCalled();
    });
  });

  // ============ 应用更改（无拒绝块时） ============
  describe('应用更改', () => {
    it('未选择任何拒绝块时点击"应用更改"显示 alert 提示', async () => {
      const chapter = makeChapter({ content: '<p>当前正文</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>旧正文</p>' })];
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByText('测试版本'));
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('应用更改')).toBeInTheDocument();
      });
      fireEvent.click(screen.getByText('应用更改'));
      expect(alertMock).toHaveBeenCalledWith('请先选择要拒绝的修改');
    });
  });

  // ============ diff 视图交互：拒绝段落 toggle / 应用更改 / 定位 ============
  describe('diff 视图交互', () => {
    it('点击拒绝按钮 toggle：第一次标记为已拒，第二次取消', async () => {
      const chapter = makeChapter({ content: '<p>当前正文</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>旧正文</p>' })];
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByText('测试版本'));
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('旧版本')).toBeInTheDocument();
      });
      // 初始未拒绝
      expect(screen.getByText('已拒 0')).toBeInTheDocument();
      // 两个不同单段内容会被合并为 1 个 modified 块，对应 1 个拒绝按钮
      const rejectBtn = screen.getByTitle('撤销此段落（回退到旧版本）');
      fireEvent.click(rejectBtn);
      expect(screen.getByText('已拒 1')).toBeInTheDocument();
      // 同一按钮 toggle：title 变为 "取消撤销"，再点击恢复
      fireEvent.click(screen.getByTitle('取消撤销'));
      expect(screen.getByText('已拒 0')).toBeInTheDocument();
    });

    it('选择拒绝段落后点击"应用更改"调用 saveVersion + updateChapterContent + bumpContentEpoch', async () => {
      const chapter = makeChapter({ content: '<p>当前正文</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>旧正文</p>' })];
      const { saveVersion, updateChapterContent, bumpContentEpoch } = mockStore({
        currentChapterId: 'ch-1',
        chapters: [chapter],
        versions,
      });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByText('测试版本'));
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('应用更改')).toBeInTheDocument();
      });
      // 先拒绝唯一一个 modified 段落
      fireEvent.click(screen.getByTitle('撤销此段落（回退到旧版本）'));
      fireEvent.click(screen.getByText('应用更改'));
      expect(saveVersion).toHaveBeenCalledWith('ch-1', '应用更改前自动备份');
      expect(updateChapterContent).toHaveBeenCalledWith('ch-1', expect.any(String));
      expect(bumpContentEpoch).toHaveBeenCalled();
      expect(alertMock).toHaveBeenCalledWith(expect.stringContaining('已成功应用更改'));
    });

    it('点击"在编辑器中定位此段落"按钮调用 setPendingScrollTo', async () => {
      const chapter = makeChapter({ content: '<p>当前正文</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>旧正文</p>' })];
      const { setPendingScrollTo } = mockStore({
        currentChapterId: 'ch-1',
        chapters: [chapter],
        versions,
      });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByText('测试版本'));
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('旧版本')).toBeInTheDocument();
      });
      // modified 块含 rightBlock（textContent='当前正文'），渲染 1 个定位按钮
      fireEvent.click(screen.getByTitle('在编辑器中定位此段落'));
      expect(setPendingScrollTo).toHaveBeenCalledWith(expect.objectContaining({
        chapterId: 'ch-1',
        blockText: '当前正文',
      }));
    });

    it('diff 视图渲染 added/removed/modified/unchanged 四类块', async () => {
      // old=[保留段, 删除段, 改旧] new=[保留段, 改新, 新增段]
      // LCS 仅 [保留段]，合并后得到：unchanged(保留段) + removed(删除段) + modified(改旧→改新) + added(新增段)
      const chapter = makeChapter({ content: '<p>保留段</p><p>改新</p><p>新增段</p>' });
      const versions = [makeVersion({ id: 'v1', content: '<p>保留段</p><p>删除段</p><p>改旧</p>' })];
      mockStore({ currentChapterId: 'ch-1', chapters: [chapter], versions });
      render(<VersionHistoryPanel />);
      fireEvent.click(screen.getByText('测试版本'));
      vi.advanceTimersByTime(50);
      await waitFor(() => {
        expect(screen.getByText('旧版本')).toBeInTheDocument();
      });
      // unchanged：左右两列均渲染“保留段”
      expect(screen.getAllByText('保留段')).toHaveLength(2);
      // removed：仅左列渲染“删除段”
      expect(screen.getByText('删除段')).toBeInTheDocument();
      // added：仅右列渲染“新增段”
      expect(screen.getByText('新增段')).toBeInTheDocument();
    });
  });
});
