/**
 * 版本与历史域 slice
 *
 * 版本快照：手动/自动保存章节内容快照，支持恢复与删除。
 * 撤销/重做：基于章节正文内容的线性历史栈（仅覆盖正文，元数据不纳入）。
 * 恢复版本会联动章节域（updateChapterContent + bumpContentEpoch）。
 */
import type { StateCreator } from 'zustand';
import type { AppState } from '../appState';
import type { ChapterVersion, Chapter } from '@/types';
import { generateId, markDirty } from '@/utils/storage';
import { HISTORY_MAX_LENGTH } from '@/constants/config';

type VersionHistorySlice = Pick<AppState,
  | 'versions' | 'histories'
  | 'saveVersion' | 'getVersions' | 'restoreVersion' | 'deleteVersion'
  | 'commitHistory' | 'undo' | 'redo' | 'canUndo' | 'canRedo'>;

export const createVersionHistorySlice: StateCreator<AppState, [], [], VersionHistorySlice> = (set, get) => ({
  versions: {},
  histories: {},

  saveVersion: (chapterId: string, description?: string) => {
    const { versions, chapters, currentProjectId } = get();
    if (!currentProjectId) return;

    const chapter = chapters.find(c => c.id === chapterId);
    if (!chapter) return;

    const chapterVersions = versions[chapterId] || [];
    const newVersion: ChapterVersion = {
      id: generateId(),
      chapterId,
      version: chapterVersions.length + 1,
      content: chapter.content,
      wordCount: chapter.wordCount,
      snapshotTime: new Date().toISOString(),
      description,
      autoGenerated: !description,
      // 记录元数据快照，使版本恢复可覆盖标题/摘要/状态等非正文字段
      metadata: {
        title: chapter.title,
        summary: chapter.summary || '',
        status: chapter.status,
        theme: chapter.theme,
        notes: chapter.notes,
      },
    };

    const updatedVersions = { ...versions, [chapterId]: [...chapterVersions, newVersion] };
    set({ versions: updatedVersions });
    markDirty();
  },

  getVersions: (chapterId: string) => {
    return get().versions[chapterId] || [];
  },

  restoreVersion: (chapterId: string, versionId: string) => {
    const { versions, chapters } = get();
    const chapterVersions = versions[chapterId] || [];
    const version = chapterVersions.find(v => v.id === versionId);
    if (!version) return;

    const chapter = chapters.find(c => c.id === chapterId);
    if (chapter) {
      get().saveVersion(chapterId, `恢复到版本 ${version.version} 前的备份`);
    }

    // 恢复正文
    get().updateChapterContent(chapterId, version.content);

    // 恢复元数据（标题/摘要/状态/主题/备注），让版本回退覆盖非正文字段
    if (version.metadata) {
      get().updateChapter(chapterId, {
        title: version.metadata.title,
        summary: version.metadata.summary,
        status: version.metadata.status as Chapter['status'],
        theme: version.metadata.theme,
        notes: version.metadata.notes,
      });
    }

    // 外部替换内容，通知编辑器强制刷新
    get().bumpContentEpoch();
  },

  deleteVersion: (chapterId: string, versionId: string) => {
    const { versions, currentProjectId } = get();
    if (!currentProjectId) return;
    const chapterVersions = versions[chapterId] || [];
    const updatedChapterVersions = chapterVersions.filter(v => v.id !== versionId);
    const updatedVersions = { ...versions, [chapterId]: updatedChapterVersions };
    set({ versions: updatedVersions });
    markDirty();
  },

  commitHistory: (chapterId: string, prevContent: string) => {
    const histories = { ...get().histories };
    const h = histories[chapterId] || { past: [], future: [], lastPush: 0 };
    const now = Date.now();
    if (now - h.lastPush > 2000) {
      h.past.push(prevContent);
      if (h.past.length > HISTORY_MAX_LENGTH) h.past.shift();
      h.future = [];
    }
    h.lastPush = now;
    histories[chapterId] = h;
    set({ histories });
  },

  undo: (chapterId: string, currentContent: string) => {
    const histories = { ...get().histories };
    const h = histories[chapterId];
    if (!h || h.past.length === 0) return null;
    h.future.unshift(currentContent);
    const prev = h.past.pop()!;
    histories[chapterId] = { ...h };
    set({ histories });
    return prev;
  },

  redo: (chapterId: string, currentContent: string) => {
    const histories = { ...get().histories };
    const h = histories[chapterId];
    if (!h || h.future.length === 0) return null;
    h.past.push(currentContent);
    const next = h.future.shift()!;
    histories[chapterId] = { ...h };
    set({ histories });
    return next;
  },

  canUndo: (chapterId: string) => {
    const h = get().histories[chapterId];
    return !!h && h.past.length > 0;
  },

  canRedo: (chapterId: string) => {
    const h = get().histories[chapterId];
    return !!h && h.future.length > 0;
  },
});
