/**
 * 版本与历史域 slice
 *
 * 版本快照：手动/自动保存章节内容快照，支持恢复与删除。
 * 撤销/重做：基于章节正文内容的线性历史栈（仅覆盖正文，元数据不纳入）。
 * 恢复版本会联动章节域（updateChapterContent + bumpContentEpoch）。
 */
import type { StateCreator } from 'zustand';
import type { AppState } from '../appState';
import type { ChapterVersion, Chapter } from '@/types';
import { CHAPTER_STATUSES } from '@/types';
import { generateId, markDirty, countWords, storage } from '@/utils/storage';
import { logError } from '@/utils/rendererLogger';
import { HISTORY_MAX_LENGTH } from '@/constants/config';

type VersionHistorySlice = Pick<AppState,
  | 'versions' | 'histories'
  | 'saveVersion' | 'getVersions' | 'restoreVersion' | 'deleteVersion'
  | 'commitHistory' | 'undo' | 'redo' | 'canUndo' | 'canRedo'>;

// 单章版本数量上限：超过时淘汰最旧版本（autoGenerated 优先），避免长期编辑后内存膨胀
const MAX_VERSIONS_PER_CHAPTER = 50;

// 裁剪单章版本列表到上限：优先淘汰 autoGenerated 的最旧版本，保留手动版本
const trimVersions = (list: ChapterVersion[]): ChapterVersion[] => {
  if (list.length <= MAX_VERSIONS_PER_CHAPTER) return list;
  const overflow = list.length - MAX_VERSIONS_PER_CHAPTER;
  // 排序：autoGenerated 排前（优先淘汰），同类按 snapshotTime 升序（旧的先淘汰）
  const evictOrder = [...list]
    .map((v, idx) => ({ v, idx }))
    .sort((a, b) => {
      if (a.v.autoGenerated !== b.v.autoGenerated) return a.v.autoGenerated ? -1 : 1;
      return (a.v.snapshotTime || '').localeCompare(b.v.snapshotTime || '');
    });
  const evictIdx = new Set(evictOrder.slice(0, overflow).map(x => x.idx));
  return list.filter((_, idx) => !evictIdx.has(idx));
};

export const createVersionHistorySlice: StateCreator<AppState, [], [], VersionHistorySlice> = (set, get) => ({
  versions: {},
  histories: {},

  saveVersion: (chapterId: string, description?: string) => {
    const { versions, chapters, currentProjectId } = get();
    if (!currentProjectId) return;

    const chapter = chapters.find(c => c.id === chapterId);
    if (!chapter) return;

    const chapterVersions = versions[chapterId] || [];
    // M12 修复：内容与最近一次版本完全相同时跳过快照创建。
    // 反复 Ctrl+S（未修改正文）不应产生重复快照，否则会挤占 MAX_VERSIONS_PER_CHAPTER
    // 上限、淘汰有价值的旧版本。仅比较 content：元数据（title/status 等）变更
    // 不应触发新快照（版本恢复以正文为主，元数据随正文恢复一并写入）。
    if (chapterVersions.length > 0) {
      const latest = chapterVersions[chapterVersions.length - 1];
      if (latest.content === chapter.content) return;
    }
    // trim 后 length 会回落，直接用 length+1 会与历史版本号重复；取最大 version + 1 保证单调递增
    // 防御 v.version 为 undefined（旧数据/损坏数据）：Math.max(max, undefined) 返回 NaN 会污染后续版本号
    const maxVersion = chapterVersions.reduce(
      (max, v) => Math.max(max, typeof v.version === 'number' && !Number.isNaN(v.version) ? v.version : 0),
      0,
    );
    const newVersion: ChapterVersion = {
      id: generateId(),
      chapterId,
      version: maxVersion + 1,
      content: chapter.content,
      wordCount: chapter.wordCount,
      snapshotTime: new Date().toISOString(),
      description,
      autoGenerated: !description,
      // 记录元数据快照，使版本恢复可覆盖标题/摘要/状态等非正文字段
      metadata: {
        title: chapter.title,
        summary: chapter.summary || '',
        status: chapter.status,
        theme: chapter.theme,
        notes: chapter.notes,
      },
    };

    const updatedVersions = { ...versions, [chapterId]: trimVersions([...chapterVersions, newVersion]) };
    set({ versions: updatedVersions });
    markDirty();
  },

  getVersions: (chapterId: string) => {
    return get().versions[chapterId] || [];
  },

  restoreVersion: (chapterId: string, versionId: string) => {
    const { versions, chapters, currentProjectId, contentEpoch, projects } = get();
    if (!currentProjectId) return;
    const chapterVersions = versions[chapterId] || [];
    const version = chapterVersions.find(v => v.id === versionId);
    if (!version) return;

    const chapter = chapters.find(c => c.id === chapterId);
    if (!chapter) return;

    const now = new Date().toISOString();

    // 1. 保存当前内容作为恢复前备份版本（内联到单次 set，避免独立 set 产生中间订阅状态）
    // trim 后 length 会回落，直接用 length+1 会与历史版本号重复；取最大 version + 1 保证单调递增
    // 防御 v.version 为 undefined（旧数据/损坏数据）：Math.max(max, undefined) 返回 NaN 会污染后续版本号
    const maxVersion = chapterVersions.reduce(
      (max, v) => Math.max(max, typeof v.version === 'number' && !Number.isNaN(v.version) ? v.version : 0),
      0,
    );
    const backupVersion: ChapterVersion = {
      id: generateId(),
      chapterId,
      version: maxVersion + 1,
      content: chapter.content,
      wordCount: chapter.wordCount,
      snapshotTime: now,
      description: `恢复到版本 ${version.version} 前的备份`,
      autoGenerated: false,
      metadata: {
        title: chapter.title,
        summary: chapter.summary || '',
        status: chapter.status,
        theme: chapter.theme,
        notes: chapter.notes,
      },
    };
    const updatedVersions = { ...versions, [chapterId]: trimVersions([...chapterVersions, backupVersion]) };

    // 2. 恢复正文 + 元数据，合并到 chapters，避免 updateChapterContent / updateChapter 各自 set
    const wordCount = countWords(version.content.replace(/<[^>]*>/g, ''));
    // 校验版本元数据中的 status：旧版本/外部数据可能写入非法值，未通过校验时回退到当前章节状态
    const rawStatus = version.metadata?.status;
    const validStatus = rawStatus && (CHAPTER_STATUSES as readonly string[]).includes(rawStatus)
      ? rawStatus as Chapter['status']
      : chapter.status;
    const updatedChapters = chapters.map(c =>
      c.id === chapterId
        ? {
            ...c,
            content: version.content,
            wordCount,
            title: version.metadata?.title ?? c.title,
            summary: version.metadata?.summary ?? c.summary,
            status: validStatus,
            theme: version.metadata?.theme ?? c.theme,
            notes: version.metadata?.notes ?? c.notes,
            updatedAt: now,
          }
        : c
    );

    // 3. 同步 project.totalWords：恢复版本只更新了 chapter.wordCount，
    // 顶栏字数（Home.tsx / EditorPage 读 project.totalWords）会与实际不一致。
    // 参考 chapterSlice.updateChapterContent 重算并写回 projects。
    const totalWords = updatedChapters.reduce((sum, c) => sum + (c.wordCount || 0), 0);
    const updatedProjects = projects.map(p =>
      p.id === currentProjectId ? { ...p, totalWords } : p
    );

    // 4. 一次性提交：chapters + contentEpoch + versions + projects，避免独立 set 让订阅者观察到中间状态
    set({
      chapters: updatedChapters,
      versions: updatedVersions,
      projects: updatedProjects,
      contentEpoch: contentEpoch + 1,
    });
    markDirty();

    // 保留原 updateChapterContent 的副作用：恢复草稿与伏笔重算（不产生 chapters/versions 的中间订阅状态）
    // H1 事务原子性：set 已原子提交（chapters/versions/projects/contentEpoch 单次 set）。
    // 后续 recomputeForeshadowMentions 为纯计算重算，若抛错不应让整个 restoreVersion 失败——
    // 章节内容已恢复是核心目标，伏笔 mentions 陈旧会在下次章节编辑时自动重算修正。
    if (get().currentChapterId === chapterId) {
      // 崩溃恢复草稿写入是异步磁盘 IO：失败时记录日志，避免 unhandledrejection
      // （仿照 chapterSlice.updateChapterContent 的处理）
      void storage.saveRecoveryDraft(currentProjectId, chapterId, version.content).catch(e => {
        logError('saveRecoveryDraft failed', e, { projectId: currentProjectId, chapterId });
      });
    }
    try {
      get().recomputeForeshadowMentions();
    } catch (e) {
      console.error('restoreVersion: recomputeForeshadowMentions failed, foreshadow mentions may be stale until next chapter edit', e);
    }
  },

  deleteVersion: (chapterId: string, versionId: string) => {
    const { versions, currentProjectId } = get();
    if (!currentProjectId) return;
    const chapterVersions = versions[chapterId] || [];
    const updatedChapterVersions = chapterVersions.filter(v => v.id !== versionId);
    const updatedVersions = { ...versions, [chapterId]: updatedChapterVersions };
    set({ versions: updatedVersions });
    markDirty();
  },

  commitHistory: (chapterId: string, prevContent: string) => {
    const histories = { ...get().histories };
    const h = histories[chapterId] || { past: [], future: [], lastPush: 0 };
    const now = Date.now();
    if (now - h.lastPush > 2000) {
      // 创建新数组，避免变异原 past/future 引用（浅拷贝会让多章节共享同一数组）
      const basePast = h.past.length >= HISTORY_MAX_LENGTH ? h.past.slice(1) : h.past;
      histories[chapterId] = {
        past: [...basePast, prevContent],
        future: [],
        lastPush: now,
      };
    } else {
      // 仅更新 lastPush，仍需创建新对象避免变异原引用
      histories[chapterId] = { ...h, lastPush: now };
    }
    set({ histories });
    // histories 变更需落盘，否则撤销/重做栈在下次启动时丢失
    markDirty();
  },

  undo: (chapterId: string, currentContent: string) => {
    const histories = { ...get().histories };
    const h = histories[chapterId];
    if (!h || h.past.length === 0) return null;
    // 创建新的 past/future 数组，避免变异原数组导致跨章节共享引用被污染
    const newPast = [...h.past];
    const prev = newPast.pop()!;
    const newFuture = [currentContent, ...h.future];
    histories[chapterId] = { past: newPast, future: newFuture, lastPush: h.lastPush };
    set({ histories });
    // histories 变更需落盘，否则撤销栈在下次启动时丢失
    markDirty();
    return prev;
  },

  redo: (chapterId: string, currentContent: string) => {
    const histories = { ...get().histories };
    const h = histories[chapterId];
    if (!h || h.future.length === 0) return null;
    // 创建新的 past/future 数组，避免变异原数组
    const newFuture = [...h.future];
    const next = newFuture.shift()!;
    const newPast = [...h.past, currentContent];
    histories[chapterId] = { past: newPast, future: newFuture, lastPush: h.lastPush };
    set({ histories });
    // histories 变更需落盘，否则重做栈在下次启动时丢失
    markDirty();
    return next;
  },

  canUndo: (chapterId: string) => {
    const h = get().histories[chapterId];
    return !!h && h.past.length > 0;
  },

  canRedo: (chapterId: string) => {
    const h = get().histories[chapterId];
    return !!h && h.future.length > 0;
  },
});
