/**
 * src/store/slices/versionHistorySlice.ts 单元测试
 *
 * 测试目标：
 * - saveVersion：保存快照、markDirty、version 单调递增、超过 50 个时淘汰 autoGenerated
 * - getVersions：返回版本列表或空数组
 * - restoreVersion：无项目/无章节/无版本时安全 noop；成功路径含备份、元数据恢复、
 *                   totalWords 同步、contentEpoch bump、markDirty、非法 status 回退
 * - deleteVersion：移除版本、markDirty
 * - commitHistory：创建 past 条目、清空 future、2s 内节流、超过 HISTORY_MAX_LENGTH 裁剪
 * - undo/redo/canUndo/canRedo：栈操作与状态查询
 *
 * 复用 projectSlice.test.ts 的 storage mock 模式：通过 vi.mock('@/utils/storage')
 * 替换 storage + markDirty 为内存实现 + no-op，避免 30s 自动保存计时器干扰。
 */
import { describe, it, expect, beforeEach, vi } from 'vitest';
import { useAppStore } from '@/store/useAppStore';
import { HISTORY_MAX_LENGTH } from '@/constants/config';
import { DEFAULT_AI_SETTINGS } from '@/store/appState';
import type { Chapter, ChapterVersion, Project } from '@/types';

// ============ 内存存储 mock ============
const { memoryStore, mockStorage } = vi.hoisted(() => {
  const memoryStore = new Map<string, unknown>();
  const mockStorage = {
    get: vi.fn(async <T>(key: string, defaultValue: T): Promise<T> => {
      return memoryStore.has(key) ? (memoryStore.get(key) as T) : defaultValue;
    }),
    set: vi.fn(async (key: string, value: unknown): Promise<void> => {
      memoryStore.set(key, value);
    }),
    remove: vi.fn(async (key: string): Promise<void> => {
      memoryStore.delete(key);
    }),
    saveRecoveryDraft: vi.fn().mockResolvedValue(undefined),
    loadRecoveryDraft: vi.fn().mockResolvedValue(null),
    clearRecoveryDraft: vi.fn().mockResolvedValue(undefined),
    saveAISettings: vi.fn().mockResolvedValue(true),
    loadAISettings: vi.fn().mockResolvedValue(null),
  };
  return { memoryStore, mockStorage };
});

vi.mock('@/utils/storage', async (importOriginal) => {
  const actual = await importOriginal<typeof import('@/utils/storage')>();
  return {
    ...actual,
    storage: mockStorage,
    // no-op：避免 30s 自动保存计时器在测试中触发
    markDirty: vi.fn(),
    triggerSave: vi.fn(async () => {}),
    clearAutoSaveTimer: vi.fn(),
  };
});

// ============ 测试辅助 ============
const makeChapter = (overrides: Partial<Chapter> = {}): Chapter => ({
  id: 'ch1',
  projectId: 'p1',
  parentId: null,
  title: '第一章',
  summary: '',
  order: 0,
  level: 1,
  levelType: 'chapter',
  status: 'draft',
  wordCount: 0,
  content: '',
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  ...overrides,
});

const makeProject = (overrides: Partial<Project> = {}): Project => ({
  id: 'p1',
  title: '测试项目',
  description: '',
  template: 'blank',
  lastOpenedAt: '',
  totalWords: 0,
  config: {
    theme: 'dark',
    fontSize: 16,
    lineHeight: 1.8,
    fontFamily: 'system-ui',
    showLineNumbers: false,
    showWordCount: true,
    zenMode: false,
    aiSettings: { ...DEFAULT_AI_SETTINGS } as never,
  },
  createdAt: '2024-01-01T00:00:00.000Z',
  updatedAt: '2024-01-01T00:00:00.000Z',
  ...overrides,
});

// ============ 测试前重置 store ============
beforeEach(() => {
  memoryStore.clear();
  mockStorage.get.mockClear();
  mockStorage.set.mockClear();
  mockStorage.remove.mockClear();
  mockStorage.saveRecoveryDraft.mockClear();

  useAppStore.setState({
    projects: [makeProject()],
    currentProjectId: 'p1',
    currentProjectFilePath: null,
    lastSavedAt: null,
    isSaving: false,
    chapters: [makeChapter()],
    currentChapterId: 'ch1',
    versions: {},
    histories: {},
    contentEpoch: 0,
    characters: [],
    settingCategories: [],
    settingItems: [],
    foreshadows: [],
    materials: [],
    conflicts: [],
    aiSuggestions: [],
    isAIGenerating: false,
    searchQuery: '',
    searchResults: [],
    analysis: {},
    subplots: [],
    updateSchedule: null,
  });
});

// ============ 测试用例 ============

describe('versionHistorySlice', () => {
  // -------------------- saveVersion --------------------
  describe('saveVersion', () => {
    it('保存版本到 versions[chapterId]', () => {
      useAppStore.setState({
        chapters: [makeChapter({ id: 'ch1', content: '内容v1', wordCount: 2 })],
      });
      useAppStore.getState().saveVersion('ch1', '手动版本');
      const versions = useAppStore.getState().versions['ch1'];
      expect(versions).toHaveLength(1);
      expect(versions[0].content).toBe('内容v1');
      expect(versions[0].description).toBe('手动版本');
      expect(versions[0].autoGenerated).toBe(false);
    });

    it('无 description 时 autoGenerated=true', () => {
      useAppStore.setState({
        chapters: [makeChapter({ id: 'ch1', content: '自动保存' })],
      });
      useAppStore.getState().saveVersion('ch1');
      const versions = useAppStore.getState().versions['ch1'];
      expect(versions[0].autoGenerated).toBe(true);
    });

    it('version 号单调递增（不依赖 length）', () => {
      useAppStore.setState({
        chapters: [makeChapter({ id: 'ch1', content: 'v1' })],
      });
      useAppStore.getState().saveVersion('ch1');
      // M12 修复后需变更内容才会产生新快照
      useAppStore.setState({ chapters: [makeChapter({ id: 'ch1', content: 'v2' })] });
      useAppStore.getState().saveVersion('ch1');
      const versions = useAppStore.getState().versions['ch1'];
      expect(versions[0].version).toBe(1);
      expect(versions[1].version).toBe(2);
    });

    it('version 号在 trim 后仍单调递增', () => {
      // 注入 49 个版本（autoGenerated=true），再 saveVersion 两次触发 trim
      const existing: ChapterVersion[] = Array.from({ length: 49 }, (_, i) => ({
        id: `v${i + 1}`,
        chapterId: 'ch1',
        version: i + 1,
        content: `content${i}`,
        wordCount: 0,
        snapshotTime: `2024-01-01T00:00:0${i % 10}.000Z`,
        autoGenerated: true,
      }));
      useAppStore.setState({
        chapters: [makeChapter({ id: 'ch1', content: 'new' })],
        versions: { ch1: existing },
      });
      useAppStore.getState().saveVersion('ch1', '手动1');
      // M12 修复后需变更内容才会产生新快照
      useAppStore.setState({ chapters: [makeChapter({ id: 'ch1', content: 'new2' })] });
      useAppStore.getState().saveVersion('ch1', '手动2');
      const versions = useAppStore.getState().versions['ch1'];
      // 最大 version 应为 51（49 + 2）
      expect(Math.max(...versions.map(v => v.version))).toBe(51);
    });

    it('M12 修复：内容与最近版本相同时跳过快照（反复 Ctrl+S 不产生重复）', () => {
      useAppStore.setState({
        chapters: [makeChapter({ id: 'ch1', content: '相同内容' })],
      });
      useAppStore.getState().saveVersion('ch1', '第一次');
      useAppStore.getState().saveVersion('ch1', '第二次');
      useAppStore.getState().saveVersion('ch1', '第三次');
      const versions = useAppStore.getState().versions['ch1'];
      // 内容未变，仅保留第一个快照
      expect(versions).toHaveLength(1);
      expect(versions[0].description).toBe('第一次');
    });

    it('M12 修复：内容变更后产生新快照', () => {
      useAppStore.setState({
        chapters: [makeChapter({ id: 'ch1', content: '内容A' })],
      });
      useAppStore.getState().saveVersion('ch1');
      expect(useAppStore.getState().versions['ch1']).toHaveLength(1);

      useAppStore.setState({ chapters: [makeChapter({ id: 'ch1', content: '内容B' })] });
      useAppStore.getState().saveVersion('ch1');
      expect(useAppStore.getState().versions['ch1']).toHaveLength(2);

      // 内容再次相同（与最近版本「内容B」相同）→ 跳过
      useAppStore.setState({ chapters: [makeChapter({ id: 'ch1', content: '内容B' })] });
      useAppStore.getState().saveVersion('ch1');
      expect(useAppStore.getState().versions['ch1']).toHaveLength(2);
    });

    it('保存元数据快照（title/summary/status/theme/notes）', () => {
      useAppStore.setState({
        chapters: [makeChapter({
          id: 'ch1',
          content: '内容',
          title: '测试标题',
          summary: '测试摘要',
          status: 'writing',
          theme: '黑暗主题',
          notes: '备注',
        })],
      });
      useAppStore.getState().saveVersion('ch1', '描述');
      const v = useAppStore.getState().versions['ch1'][0];
      expect(v.metadata).toMatchObject({
        title: '测试标题',
        summary: '测试摘要',
        status: 'writing',
        theme: '黑暗主题',
        notes: '备注',
      });
    });

    it('无 currentProjectId 时 noop', () => {
      useAppStore.setState({ currentProjectId: null });
      useAppStore.getState().saveVersion('ch1');
      expect(useAppStore.getState().versions['ch1']).toBeUndefined();
    });

    it('章节不存在时 noop', () => {
      useAppStore.getState().saveVersion('not-exist');
      expect(useAppStore.getState().versions['ch1']).toBeUndefined();
    });
  });

  // -------------------- trimVersions（超过 50 淘汰 autoGenerated） --------------------
  describe('trimVersions', () => {
    it('超过 50 个时淘汰最旧的 autoGenerated 版本', () => {
      // 注入 50 个 autoGenerated 版本 + 5 个手动版本，共 55 个
      const existing: ChapterVersion[] = [
        ...Array.from({ length: 50 }, (_, i) => ({
          id: `auto-${i + 1}`,
          chapterId: 'ch1',
          version: i + 1,
          content: `auto${i}`,
          wordCount: 0,
          snapshotTime: `2024-01-01T00:00:0${i % 10}.000Z`,
          autoGenerated: true,
        })),
        ...Array.from({ length: 5 }, (_, i) => ({
          id: `manual-${i + 1}`,
          chapterId: 'ch1',
          version: 51 + i,
          content: `manual${i}`,
          wordCount: 0,
          snapshotTime: `2024-01-01T00:00:0${i % 10}.000Z`,
          autoGenerated: false,
          description: `手动${i}`,
        })),
      ];
      useAppStore.setState({
        chapters: [makeChapter({ id: 'ch1', content: 'new' })],
        versions: { ch1: existing },
      });
      // 再保存一个触发 trim
      useAppStore.getState().saveVersion('ch1', '触发裁剪');
      const versions = useAppStore.getState().versions['ch1'];
      // 应裁剪到 50 个
      expect(versions).toHaveLength(50);
      // 5 个手动版本应全部保留
      const manualCount = versions.filter(v => !v.autoGenerated).length;
      expect(manualCount).toBe(6); // 5 个原有 + 1 个新保存
    });
  });

  // -------------------- getVersions --------------------
  describe('getVersions', () => {
    it('返回 versions[chapterId]', () => {
      const v: ChapterVersion[] = [{
        id: 'v1', chapterId: 'ch1', version: 1, content: 'c',
        wordCount: 1, snapshotTime: '2024-01-01', autoGenerated: false,
      }];
      useAppStore.setState({ versions: { ch1: v } });
      expect(useAppStore.getState().getVersions('ch1')).toEqual(v);
    });

    it('chapterId 不存在时返回空数组', () => {
      expect(useAppStore.getState().getVersions('not-exist')).toEqual([]);
    });
  });

  // -------------------- restoreVersion --------------------
  describe('restoreVersion', () => {
    it('无 currentProjectId 时 noop', () => {
      const versions: ChapterVersion[] = [{
        id: 'v1', chapterId: 'ch1', version: 1, content: '历史',
        wordCount: 2, snapshotTime: '2024-01-01', autoGenerated: false,
        metadata: { title: '旧标题', summary: '', status: 'draft', theme: '', notes: '' },
      }];
      useAppStore.setState({ currentProjectId: null, versions: { ch1: versions } });
      useAppStore.getState().restoreVersion('ch1', 'v1');
      // chapters 不应变化
      expect(useAppStore.getState().chapters[0].content).toBe('');
    });

    it('版本不存在时 noop', () => {
      useAppStore.getState().restoreVersion('ch1', 'not-exist');
      expect(useAppStore.getState().chapters[0].content).toBe('');
    });

    it('章节不存在时 noop', () => {
      const versions: ChapterVersion[] = [{
        id: 'v1', chapterId: 'ch1', version: 1, content: '历史',
        wordCount: 2, snapshotTime: '2024-01-01', autoGenerated: false,
      }];
      useAppStore.setState({
        chapters: [],
        versions: { ch1: versions },
      });
      useAppStore.getState().restoreVersion('ch1', 'v1');
      // 不应抛错，versions 不变
      expect(useAppStore.getState().versions['ch1']).toHaveLength(1);
    });

    it('成功恢复：写入正文 + 元数据 + 备份版本', () => {
      const original = useAppStore.getState().chapters[0];
      useAppStore.setState({
        chapters: [makeChapter({
          id: 'ch1',
          content: '当前内容',
          title: '当前标题',
          status: 'writing',
          wordCount: 4,
        })],
        versions: {
          ch1: [{
            id: 'v1', chapterId: 'ch1', version: 1, content: '历史正文',
            wordCount: 4, snapshotTime: '2024-01-01', autoGenerated: false,
            metadata: { title: '历史标题', summary: '历史摘要', status: 'done', theme: '历史主题', notes: '历史备注' },
          }],
        },
      });
      useAppStore.getState().restoreVersion('ch1', 'v1');
      const state = useAppStore.getState();
      // 章节内容被恢复
      const ch = state.chapters.find(c => c.id === 'ch1')!;
      expect(ch.content).toBe('历史正文');
      expect(ch.title).toBe('历史标题');
      expect(ch.summary).toBe('历史摘要');
      expect(ch.status).toBe('done');
      expect(ch.theme).toBe('历史主题');
      expect(ch.notes).toBe('历史备注');
      // 备份版本被保存（恢复前的内容）
      const versions = state.versions['ch1'];
      expect(versions).toHaveLength(2);
      const backup = versions.find(v => v.id !== 'v1')!;
      expect(backup.content).toBe('当前内容');
      expect(backup.description).toContain('恢复到版本');
      expect(backup.autoGenerated).toBe(false);
      // contentEpoch 递增
      expect(state.contentEpoch).toBe(1);
      // original 引用未被变异
      expect(original.content).toBe('');
    });

    it('恢复时同步 project.totalWords', () => {
      useAppStore.setState({
        chapters: [
          makeChapter({ id: 'ch1', content: '当前', wordCount: 2 }),
          makeChapter({ id: 'ch2', content: '固定', wordCount: 5 }),
        ],
        versions: {
          ch1: [{
            id: 'v1', chapterId: 'ch1', version: 1, content: '历史正文较长',
            wordCount: 7, snapshotTime: '2024-01-01', autoGenerated: false,
          }],
        },
      });
      useAppStore.getState().restoreVersion('ch1', 'v1');
      const project = useAppStore.getState().projects.find(p => p.id === 'p1')!;
      // totalWords = ch1 的新 wordCount + ch2 的 wordCount
      // countWords 基于 strip HTML 后的字符，'历史正文较长' = 6 字（中文按字计）
      // 实际值取决于 countWords 实现，断言 totalWords >= 5（至少包含 ch2 的 5）
      expect(project.totalWords).toBeGreaterThanOrEqual(5);
    });

    it('恢复后调用 saveRecoveryDraft（当前章节匹配时）', async () => {
      useAppStore.setState({
        chapters: [makeChapter({ id: 'ch1', content: '当前' })],
        versions: {
          ch1: [{
            id: 'v1', chapterId: 'ch1', version: 1, content: '历史',
            wordCount: 2, snapshotTime: '2024-01-01', autoGenerated: false,
          }],
        },
        currentChapterId: 'ch1',
      });
      useAppStore.getState().restoreVersion('ch1', 'v1');
      // 等待 microtask 完成（saveRecoveryDraft 是 void 调用，但 mock 已记录）
      await Promise.resolve();
      expect(mockStorage.saveRecoveryDraft).toHaveBeenCalledWith('p1', 'ch1', '历史');
    });

    it('恢复版本 metadata.status 非法时回退到章节当前 status', () => {
      useAppStore.setState({
        chapters: [makeChapter({
          id: 'ch1',
          content: '当前',
          status: 'writing',
        })],
        versions: {
          ch1: [{
            id: 'v1', chapterId: 'ch1', version: 1, content: '历史',
            wordCount: 2, snapshotTime: '2024-01-01', autoGenerated: false,
            metadata: { title: 'T', summary: '', status: 'invalid-status' as never, theme: '', notes: '' },
          }],
        },
      });
      useAppStore.getState().restoreVersion('ch1', 'v1');
      const ch = useAppStore.getState().chapters.find(c => c.id === 'ch1')!;
      expect(ch.status).toBe('writing'); // 回退到原值
    });

    it('恢复版本无 metadata 时保留章节当前元数据', () => {
      useAppStore.setState({
        chapters: [makeChapter({
          id: 'ch1',
          content: '当前',
          title: '当前标题',
          summary: '当前摘要',
          status: 'writing',
        })],
        versions: {
          ch1: [{
            id: 'v1', chapterId: 'ch1', version: 1, content: '历史',
            wordCount: 2, snapshotTime: '2024-01-01', autoGenerated: false,
            // 无 metadata 字段
          }],
        },
      });
      useAppStore.getState().restoreVersion('ch1', 'v1');
      const ch = useAppStore.getState().chapters.find(c => c.id === 'ch1')!;
      expect(ch.title).toBe('当前标题');
      expect(ch.summary).toBe('当前摘要');
      expect(ch.status).toBe('writing');
    });
  });

  // -------------------- deleteVersion --------------------
  describe('deleteVersion', () => {
    it('从 versions[chapterId] 移除指定版本', () => {
      useAppStore.setState({
        versions: {
          ch1: [
            { id: 'v1', chapterId: 'ch1', version: 1, content: 'c1', wordCount: 0, snapshotTime: '', autoGenerated: false },
            { id: 'v2', chapterId: 'ch1', version: 2, content: 'c2', wordCount: 0, snapshotTime: '', autoGenerated: false },
          ],
        },
      });
      useAppStore.getState().deleteVersion('ch1', 'v1');
      const versions = useAppStore.getState().versions['ch1'];
      expect(versions).toHaveLength(1);
      expect(versions[0].id).toBe('v2');
    });

    it('版本不存在时安全 noop', () => {
      useAppStore.setState({
        versions: { ch1: [{ id: 'v1', chapterId: 'ch1', version: 1, content: '', wordCount: 0, snapshotTime: '', autoGenerated: false }] },
      });
      useAppStore.getState().deleteVersion('ch1', 'not-exist');
      expect(useAppStore.getState().versions['ch1']).toHaveLength(1);
    });

    it('无 currentProjectId 时 noop', () => {
      useAppStore.setState({
        currentProjectId: null,
        versions: { ch1: [{ id: 'v1', chapterId: 'ch1', version: 1, content: '', wordCount: 0, snapshotTime: '', autoGenerated: false }] },
      });
      useAppStore.getState().deleteVersion('ch1', 'v1');
      expect(useAppStore.getState().versions['ch1']).toHaveLength(1);
    });
  });

  // -------------------- commitHistory --------------------
  describe('commitHistory', () => {
    it('创建 past 条目并清空 future', () => {
      useAppStore.getState().commitHistory('ch1', '旧内容');
      const h = useAppStore.getState().histories['ch1'];
      expect(h.past).toEqual(['旧内容']);
      expect(h.future).toEqual([]);
      expect(h.lastPush).toBeGreaterThan(0);
    });

    it('2s 内连续 commit 仅更新 lastPush 不压栈', () => {
      useAppStore.getState().commitHistory('ch1', 'v1');
      const firstPush = useAppStore.getState().histories['ch1'].lastPush;
      // 立即再次 commit（在 2s 内）
      useAppStore.getState().commitHistory('ch1', 'v2');
      const h = useAppStore.getState().histories['ch1'];
      // past 不应增长
      expect(h.past).toEqual(['v1']);
      // lastPush 应更新
      expect(h.lastPush).toBeGreaterThanOrEqual(firstPush);
    });

    it('超过 2s 后 commit 压入新条目', () => {
      vi.useFakeTimers();
      const now = Date.now();
      vi.setSystemTime(now);
      useAppStore.getState().commitHistory('ch1', 'v1');
      // 前进 2.5s
      vi.setSystemTime(now + 2500);
      useAppStore.getState().commitHistory('ch1', 'v2');
      const h = useAppStore.getState().histories['ch1'];
      expect(h.past).toEqual(['v1', 'v2']);
      vi.useRealTimers();
    });

    it('超过 HISTORY_MAX_LENGTH 时裁剪最旧条目', () => {
      // 预填满 past 到 HISTORY_MAX_LENGTH
      const past: string[] = Array.from({ length: HISTORY_MAX_LENGTH }, (_, i) => `old${i}`);
      // 用 fake timers 让每次 commit 都超过 2s 间隔
      vi.useFakeTimers();
      const baseTime = Date.now();
      vi.setSystemTime(baseTime);
      useAppStore.setState({
        histories: {
          ch1: { past: [...past], future: [], lastPush: baseTime - 3000 },
        },
      });
      // 再 commit 一次（间隔 > 2s，会压栈并触发裁剪）
      useAppStore.getState().commitHistory('ch1', 'new');
      const h = useAppStore.getState().histories['ch1'];
      expect(h.past).toHaveLength(HISTORY_MAX_LENGTH);
      // 最旧的 old0 应被裁剪
      expect(h.past[0]).toBe('old1');
      expect(h.past[h.past.length - 1]).toBe('new');
      vi.useRealTimers();
    });

    it('独立章节互不影响（不共享 past/future 引用）', () => {
      useAppStore.getState().commitHistory('ch1', 'ch1-content');
      useAppStore.getState().commitHistory('ch2', 'ch2-content');
      const h1 = useAppStore.getState().histories['ch1'];
      const h2 = useAppStore.getState().histories['ch2'];
      expect(h1.past).toEqual(['ch1-content']);
      expect(h2.past).toEqual(['ch2-content']);
      // 修改 h1 不应影响 h2
      h1.past.push('mutated');
      expect(h2.past).toEqual(['ch2-content']);
    });
  });

  // -------------------- undo / redo --------------------
  describe('undo', () => {
    it('返回上一条内容并移动到 future', () => {
      useAppStore.setState({
        histories: {
          ch1: { past: ['old1', 'old2'], future: [], lastPush: 0 },
        },
      });
      const prev = useAppStore.getState().undo('ch1', 'current');
      expect(prev).toBe('old2');
      const h = useAppStore.getState().histories['ch1'];
      expect(h.past).toEqual(['old1']);
      expect(h.future).toEqual(['current']);
    });

    it('past 为空时返回 null', () => {
      useAppStore.setState({
        histories: { ch1: { past: [], future: [], lastPush: 0 } },
      });
      const result = useAppStore.getState().undo('ch1', 'current');
      expect(result).toBeNull();
    });

    it('章节无 history 时返回 null', () => {
      const result = useAppStore.getState().undo('not-exist', 'current');
      expect(result).toBeNull();
    });

    it('undo 不变异原 past 数组（避免跨章节共享污染）', () => {
      const originalPast = ['old1', 'old2'];
      useAppStore.setState({
        histories: { ch1: { past: originalPast, future: [], lastPush: 0 } },
      });
      useAppStore.getState().undo('ch1', 'current');
      // 原 past 数组引用不应被变异
      expect(originalPast).toEqual(['old1', 'old2']);
    });
  });

  describe('redo', () => {
    it('返回下一条内容并移动到 past', () => {
      useAppStore.setState({
        histories: {
          ch1: { past: ['old1'], future: ['future1', 'future2'], lastPush: 0 },
        },
      });
      const next = useAppStore.getState().redo('ch1', 'current');
      expect(next).toBe('future1');
      const h = useAppStore.getState().histories['ch1'];
      expect(h.past).toEqual(['old1', 'current']);
      expect(h.future).toEqual(['future2']);
    });

    it('future 为空时返回 null', () => {
      useAppStore.setState({
        histories: { ch1: { past: [], future: [], lastPush: 0 } },
      });
      const result = useAppStore.getState().redo('ch1', 'current');
      expect(result).toBeNull();
    });

    it('章节无 history 时返回 null', () => {
      const result = useAppStore.getState().redo('not-exist', 'current');
      expect(result).toBeNull();
    });

    it('redo 不变异原 future 数组', () => {
      const originalFuture = ['f1', 'f2'];
      useAppStore.setState({
        histories: { ch1: { past: [], future: originalFuture, lastPush: 0 } },
      });
      useAppStore.getState().redo('ch1', 'current');
      expect(originalFuture).toEqual(['f1', 'f2']);
    });
  });

  // -------------------- canUndo / canRedo --------------------
  describe('canUndo / canRedo', () => {
    it('canUndo：past 非空返回 true', () => {
      useAppStore.setState({
        histories: { ch1: { past: ['x'], future: [], lastPush: 0 } },
      });
      expect(useAppStore.getState().canUndo('ch1')).toBe(true);
    });

    it('canUndo：past 为空返回 false', () => {
      useAppStore.setState({
        histories: { ch1: { past: [], future: [], lastPush: 0 } },
      });
      expect(useAppStore.getState().canUndo('ch1')).toBe(false);
    });

    it('canUndo：章节无 history 返回 false', () => {
      expect(useAppStore.getState().canUndo('not-exist')).toBe(false);
    });

    it('canRedo：future 非空返回 true', () => {
      useAppStore.setState({
        histories: { ch1: { past: [], future: ['x'], lastPush: 0 } },
      });
      expect(useAppStore.getState().canRedo('ch1')).toBe(true);
    });

    it('canRedo：future 为空返回 false', () => {
      useAppStore.setState({
        histories: { ch1: { past: [], future: [], lastPush: 0 } },
      });
      expect(useAppStore.getState().canRedo('ch1')).toBe(false);
    });

    it('canRedo：章节无 history 返回 false', () => {
      expect(useAppStore.getState().canRedo('not-exist')).toBe(false);
    });
  });
});
