export interface Project {
  id: string;
  title: string;
  description: string;
  template: 'blank' | 'three-act' | 'hero-journey' | 'chapter';
  cover?: string;
  createdAt: string;
  updatedAt: string;
  lastOpenedAt: string;
  totalWords: number;
  config: ProjectConfig;
}

export interface ProjectConfig {
  theme: 'dark' | 'light';
  fontSize: number;
  lineHeight: number;
  fontFamily: string;
  showLineNumbers: boolean;
  showWordCount: boolean;
  zenMode: boolean;
  aiSettings: AISettings;
}

export interface AISettings {
  provider: 'mock' | 'openai' | 'local' | 'deepseek';
  apiKey?: string;
  baseUrl?: string;
  model?: string;
  style: 'balanced' | 'action' | 'psychology' | 'description';
  descriptionDensity: number;
  dialogueDensity: number;
  strictness: number;
  temperature: number;
  maxTokens: number;
  autoCheckConflicts: boolean;
}

export type ChapterLevelType = 'book' | 'volume' | 'part' | 'section' | 'chapter';

export interface Chapter {
  id: string;
  projectId: string;
  parentId: string | null;
  title: string;
  summary: string;
  order: number;
  level: number;
  levelType: ChapterLevelType;
  status: 'draft' | 'writing' | 'reviewing' | 'done';
  wordCount: number;
  content: string;
  perspective?: string;
  createdAt: string;
  updatedAt: string;
  children?: Chapter[];
  wordTarget?: number;
  timeSpan?: string;
  theme?: string;
  coreProposition?: string;
  epigraph?: string;
  characterFocus?: string[];
  keyEvents?: string[];
  foreshadows?: string[];
  notes?: string;
}

export interface ChapterVersion {
  id: string;
  chapterId: string;
  version: number;
  content: string;
  wordCount: number;
  snapshotTime: string;
  description?: string;
  autoGenerated: boolean;
  /** 元数据快照：用于恢复标题/摘要/状态等非正文字段（旧版本可能缺失） */
  metadata?: {
    title: string;
    summary: string;
    status: string;
    theme?: string;
    notes?: string;
  };
}

export interface Character {
  id: string;
  projectId: string;
  name: string;
  role: 'protagonist' | 'antagonist' | 'supporting' | 'minor' | 'narrator';
  avatar?: string;
  color: string;
  profile: CharacterProfile;
  relationships: CharacterRelationship[];
  appearanceCount: number;
  dialogueCount: number;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

export interface CharacterProfile {
  age?: string;
  gender?: string;
  appearance?: string;
  personality?: string;
  background?: string;
  motivation?: string;
  goal?: string;
  weakness?: string;
  fear?: string;
  arc?: string;
  occupation?: string;
  skills?: string;
  [key: string]: string | undefined;
}

export interface CharacterRelationship {
  targetId: string;
  type: string;
  description: string;
  intensity: number;
}

export interface SettingCategory {
  id: string;
  projectId: string;
  name: string;
  icon: string;
  color: string;
  order: number;
  parentId: string | null;
}

export interface SettingItem {
  id: string;
  projectId: string;
  categoryId: string;
  name: string;
  description: string;
  content: string;
  icon?: string;
  color?: string;
  references: string[];
  tags: string[];
  order: number;
  createdAt: string;
  updatedAt: string;
}

export interface Foreshadow {
  id: string;
  projectId: string;
  title: string;
  description: string;
  status: 'planted' | 'progressing' | 'paid-off' | 'abandoned';
  plantedChapterId: string | null;
  payoffChapterId: string | null;
  priority: 'high' | 'medium' | 'low';
  relatedCharacters: string[];
  relatedSettings: string[];
  chaptersSinceMention: number;
  notes: string;
  createdAt: string;
  updatedAt: string;
}

export interface MaterialAttachment {
  id: string;
  name: string;
  path: string;       // 本地文件原始路径
  size: number;
  ext: string;
  addedAt: string;
}

export interface Material {
  id: string;
  projectId: string;
  title: string;
  type: 'inspiration' | 'reference' | 'research' | 'quote' | 'image' | 'audio';
  content: string;
  source?: string;
  url?: string;
  tags: string[];
  category: string;
  references: string[];
  pinned: boolean;
  createdAt: string;
  updatedAt: string;
  // 图片/文件附件走本地文件路径（MaterialAttachment.path），不再内嵌 base64，避免体积膨胀与注入风险
  attachments?: MaterialAttachment[];
}

export interface SearchResult {
  type: 'chapter' | 'character' | 'setting' | 'foreshadow' | 'material';
  id: string;
  title: string;
  preview: string;
  matchCount: number;
}

export interface ConflictIssue {
  id: string;
  type: 'character' | 'timeline' | 'setting' | 'style' | 'logic';
  severity: 'error' | 'warning' | 'info';
  chapterId: string;
  description: string;
  suggestion: string;
  position?: { start: number; end: number };
  resolved: boolean;
}

export interface AISuggestion {
  id: string;
  type: 'continue' | 'expand' | 'polish' | 'perspective' | 'suggestion' | 'fix';
  title: string;
  content: string;
  originalText?: string;
  reasoning: string;
  contextUsed: string[];
  timestamp: string;
}

export interface ChapterAnalysis {
  chapterId: string;
  wordCount: number;
  readingTime: number;
  emotionScore: number;
  conflictIntensity: number;
  hookStrength: number;
  pacingScore: number;
  dialogueRatio: number;
  descriptionRatio: number;
  characters: string[];
  settings: string[];
  foreshadows: string[];
}

export interface ExportConfig {
  format: 'markdown' | 'docx' | 'pdf' | 'epub' | 'txt';
  includeToc: boolean;
  includeCover: boolean;
  chapterLevel: number;
  style: 'novel' | 'article' | 'script';
  font: string;
  fontSize: number;
  lineHeight: number;
  margins: {
    top: number;
    bottom: number;
    left: number;
    right: number;
  };
  platformPreset?: 'qidian' | 'fanqie' | 'wechat' | 'general';
}

export const CHAPTER_LEVEL_TYPE_LABELS: Record<ChapterLevelType, string> = {
  book: '全书',
  volume: '卷',
  part: '部',
  section: '节',
  chapter: '章',
};

export const CHAPTER_LEVEL_TYPE_COLORS: Record<ChapterLevelType, string> = {
  book: 'text-amber-400 bg-amber-400/10',
  volume: 'text-blue-400 bg-blue-400/10',
  part: 'text-purple-400 bg-purple-400/10',
  section: 'text-cyan-400 bg-cyan-400/10',
  chapter: 'text-ink-300 bg-ink-700/30',
};

export const CHAPTER_STATUS_LABELS: Record<Chapter['status'], string> = {
  draft: '草稿',
  writing: '写作中',
  reviewing: '待审',
  done: '已完成',
};

export const CHAPTER_STATUS_COLORS: Record<Chapter['status'], string> = {
  draft: 'bg-gray-500',
  writing: 'bg-amber-500',
  reviewing: 'bg-blue-500',
  done: 'bg-emerald-500',
};

export const FORESHADOW_STATUS_LABELS: Record<Foreshadow['status'], string> = {
  planted: '已埋设',
  progressing: '推进中',
  'paid-off': '已回收',
  abandoned: '已废弃',
};

export const CHARACTER_ROLE_LABELS: Record<Character['role'], string> = {
  protagonist: '主角',
  antagonist: '反派',
  supporting: '配角',
  minor: '龙套',
  narrator: '叙述者',
};

export const MATERIAL_TYPE_LABELS: Record<Material['type'], string> = {
  inspiration: '灵感',
  reference: '参考资料',
  research: '研究笔记',
  quote: '摘抄',
  image: '图片',
  audio: '音频',
};

// ==================== 值常量（用于迭代、校验、默认值）====================
export const CHARACTER_ROLES = ['protagonist', 'antagonist', 'supporting', 'minor', 'narrator'] as const;
export const CHAPTER_STATUSES = ['draft', 'writing', 'reviewing', 'done'] as const;
export const FORESHADOW_STATUSES = ['planted', 'progressing', 'paid-off', 'abandoned'] as const;
export const MATERIAL_TYPES = ['inspiration', 'reference', 'research', 'quote', 'image', 'audio'] as const;
export const CHAPTER_LEVEL_TYPES = ['book', 'volume', 'part', 'section', 'chapter'] as const;

// level 数字 → levelType 的映射工具，保证 moveChapter/addChapter 等场景 level 与 levelType 始终一致
export const levelToLevelType = (level: number): ChapterLevelType => {
  const idx = Math.min(Math.max(level, 1), CHAPTER_LEVEL_TYPES.length) - 1;
  return CHAPTER_LEVEL_TYPES[idx];
};
export const FORESHADOW_PRIORITIES = ['high', 'medium', 'low'] as const;

// 默认值常量（统一管理，避免散落的魔法字符串）
export const DEFAULT_CHARACTER_ROLE: Character['role'] = 'supporting';
export const DEFAULT_CHAPTER_STATUS: Chapter['status'] = 'draft';
export const DEFAULT_FORESHADOW_STATUS: Foreshadow['status'] = 'planted';
export const DEFAULT_FORESHADOW_PRIORITY: Foreshadow['priority'] = 'medium';
export const DEFAULT_MATERIAL_TYPE: Material['type'] = 'inspiration';
