import type { ChapterVersion } from '@/types';

/**
 * 版本历史增量 Diff 存储工具
 *
 * 背景：每个版本快照原本都存完整内容，长篇作品多版本后数据体积快速膨胀。
 * 方案：首个版本保留完整内容作为基线，后续版本仅存与前一版本的 diff；
 *      读取时按链式重建出每个版本的完整内容。
 *
 * 公共 API：
 *   - encodeVersionsToDeltas(versions) 将内存中的完整版本序列压缩为存储形式
 *   - decodeDeltasToVersions(stored)   将存储形式重建为完整版本序列
 *
 * diff 格式（字符串）：
 *   新格式：JSON.stringify({ p: prefixLen, a: aMid, b: bMid, s: suffixLen })
 *     - p: 公共前缀长度
 *     - a: 旧版本中间被替换的片段
 *     - b: 新版本中间替换后的片段
 *     - s: 公共后缀长度
 *   完全相同时存空字符串以避免重复内容。
 *   JSON.stringify 自动处理所有特殊字符，彻底消除分隔符歧义。
 *
 * 兼容性：
 *   - delta 字段为 null/undefined 时按"完整内容"处理，旧文件可直接读取。
 *   - 旧格式 `<prefixLen>\u0000<aMid>\u0001<bMid>\u0001<suffixLen>` 仍可解析
 *     （aMid/bMid 未转义，仅适用于内容中不含 \u0001 的旧数据）。
 */

// 控制字符：仅用于解析旧格式 delta 的向后兼容。
// 新格式使用 JSON，不再依赖分隔符，也无需转义。
const SEP_MID = '\u0000';
const SEP_PART = '\u0001';

export interface StoredVersion {
  id: string;
  chapterId: string;
  version: number;
  content: string;
  // null/undefined => content 为完整内容（基线或旧文件兼容）
  // string         => content 为空，需用 delta 与前一版本重建
  delta: string | null;
  wordCount: number;
  snapshotTime: string;
  description?: string;
  autoGenerated: boolean;
}

/**
 * decodeDeltasToVersions 的输入类型。
 *
 * 兼容两种来源：
 *   - encodeVersionsToDeltas 产出的 StoredVersion[]（含 delta 字段，新写入的数据）
 *   - localStorage 中按 ChapterVersion[] 类型读出的旧数据（TS 类型不含 delta，
 *     但运行时可能仍是 StoredVersion[]；旧文件无 delta 字段时按基线处理）
 *
 * 将 delta 设为可选，使 ChapterVersion[] 可直接传入，无需 `as unknown as` 双重断言；
 * 运行时 delta 为 undefined 时 decodeDeltasToVersions 走"完整内容"基线分支。
 */
export type VersionDeltaPayload = Omit<StoredVersion, 'delta'> & { delta?: string | null };

// 计算两段文本的 diff：前缀/后缀保留，中间替换段单独存储
function computeSimpleDiff(a: string, b: string): string {
  if (a === b) return ''; // 完全相同，无需任何替换
  const minLen = Math.min(a.length, b.length);
  let prefixLen = 0;
  while (prefixLen < minLen && a[prefixLen] === b[prefixLen]) prefixLen++;
  let suffixLen = 0;
  while (suffixLen < minLen - prefixLen && a[a.length - 1 - suffixLen] === b[b.length - 1 - suffixLen]) suffixLen++;
  const aMid = a.slice(prefixLen, a.length - suffixLen);
  const bMid = b.slice(prefixLen, b.length - suffixLen);
  // JSON 序列化整个对象，自动处理所有特殊字符，彻底消除分隔符歧义
  return JSON.stringify({ p: prefixLen, a: aMid, b: bMid, s: suffixLen });
}

// 将 diff 应用到基线，重建出新版本内容。delta 损坏时抛错而非静默回退，避免产生错误内容。
function applySimpleDiff(base: string, delta: string): string {
  if (delta === '') return base;
  // 新格式：JSON 对象 { p, a, b, s }
  if (delta.startsWith('{')) {
    let parsed: { p?: unknown; a?: unknown; b?: unknown; s?: unknown };
    try {
      parsed = JSON.parse(delta);
    } catch {
      throw new Error('Invalid delta: JSON parse failed');
    }
    const prefixLen = Number(parsed.p);
    const suffixLen = Number(parsed.s);
    if (!Number.isInteger(prefixLen) || prefixLen < 0) {
      throw new Error('Invalid delta: invalid prefix length');
    }
    if (!Number.isInteger(suffixLen) || suffixLen < 0) {
      throw new Error('Invalid delta: invalid suffix length');
    }
    if (typeof parsed.a !== 'string' || typeof parsed.b !== 'string') {
      throw new Error('Invalid delta: a/b must be strings');
    }
    if (prefixLen + suffixLen > base.length) {
      throw new Error('Invalid delta: length out of range for base');
    }
    return base.slice(0, prefixLen) + parsed.b + base.slice(base.length - suffixLen);
  }
  // 旧格式向后兼容：<prefixLen>\u0000<aMid>\u0001<bMid>\u0001<suffixLen>
  // 注意：旧格式对 aMid/bMid 中的分隔符做 SQL 风格加倍转义，存在转义歧义 bug。
  // 此处仅做尽力解析（简单 split），含 \u0001 的旧 delta 会因 parts.length !== 3 抛错。
  const sepMidIdx = delta.indexOf(SEP_MID);
  if (sepMidIdx < 0) {
    throw new Error('Invalid delta: missing SEP_MID boundary');
  }
  const prefixLen = parseInt(delta.slice(0, sepMidIdx), 10);
  if (Number.isNaN(prefixLen) || prefixLen < 0) {
    throw new Error('Invalid delta: invalid prefix length');
  }
  const parts = delta.slice(sepMidIdx + 1).split(SEP_PART);
  if (parts.length !== 3) {
    throw new Error('Invalid delta: expected 3 parts after SEP_MID');
  }
  const bMid = parts[1];
  const suffixLen = parseInt(parts[2], 10);
  if (Number.isNaN(suffixLen) || suffixLen < 0) {
    throw new Error('Invalid delta: invalid suffix length');
  }
  if (prefixLen + suffixLen > base.length) {
    throw new Error('Invalid delta: length out of range for base');
  }
  return base.slice(0, prefixLen) + bMid + base.slice(base.length - suffixLen);
}

export function encodeVersionsToDeltas(versions: ChapterVersion[]): StoredVersion[] {
  if (versions.length === 0) return [];
  const result: StoredVersion[] = [];
  let prevContent = '';
  for (let i = 0; i < versions.length; i++) {
    const v = versions[i];
    if (i === 0) {
      // 首个版本保留完整内容作为基线
      result.push({ ...v, delta: null });
    } else {
      // 后续版本仅存与前一版本的 diff，content 字段留空
      result.push({ ...v, content: '', delta: computeSimpleDiff(prevContent, v.content) });
    }
    prevContent = v.content;
  }
  return result;
}

export function decodeDeltasToVersions(stored: VersionDeltaPayload[]): ChapterVersion[] {
  if (stored.length === 0) return [];
  const result: ChapterVersion[] = [];
  let prevContent = '';
  for (const s of stored) {
    let content: string;
    if (s.delta === null || s.delta === undefined) {
      // 兼容旧文件：无 delta 字段时 content 即完整内容
      content = s.content;
    } else {
      // 单个 delta 解析失败时降级保留前一版本内容，避免一个坏 delta 拖垮整条链
      // 导致用户丢失全部版本历史（旧格式 aMid/bMid 含 \u0001 时会抛
      // "expected 3 parts after SEP_MID"）
      try {
        content = applySimpleDiff(prevContent, s.delta);
      } catch (e) {
        console.warn('decodeDeltasToVersions: delta parse failed, fallback to prevContent:', e);
        content = prevContent;
      }
    }
    // 重建出的 ChapterVersion 不带 delta 字段；_delta 仅为剔除字段而解构
     
    const { delta: _delta, ...rest } = s;
    result.push({ ...rest, content });
    prevContent = content;
  }
  return result;
}
