import { encodeVersionsToDeltas, decodeDeltasToVersions } from '@/utils/versionDelta';
import type { StoredVersion } from '@/utils/versionDelta';
import type { ChapterVersion } from '@/types';

// 辅助：构造 ChapterVersion
function makeVersion(id: string, content: string, version: number = 1): ChapterVersion {
  return {
    id,
    chapterId: 'chapter-1',
    version,
    content,
    wordCount: content.length,
    snapshotTime: `2024-01-0${version}T00:00:00.000Z`,
    autoGenerated: false,
  };
}

// 辅助：构造 StoredVersion（用于手动构造损坏 delta 等场景）
function makeStored(
  id: string,
  content: string,
  delta: string | null,
  version: number = 1,
): StoredVersion {
  return {
    id,
    chapterId: 'chapter-1',
    version,
    content,
    delta,
    wordCount: content.length,
    snapshotTime: `2024-01-0${version}T00:00:00.000Z`,
    autoGenerated: false,
  };
}

describe('versionDelta', () => {
  describe('基础编码解码', () => {
    it('3 个 Version 编码后解码应恢复出相同 content', () => {
      // Arrange
      const versions: ChapterVersion[] = [
        makeVersion('v1', 'Hello World', 1),
        makeVersion('v2', 'Hello JavaScript World', 2),
        makeVersion('v3', 'Hello TypeScript World!', 3),
      ];

      // Act
      const stored = encodeVersionsToDeltas(versions);
      const decoded = decodeDeltasToVersions(stored);

      // Assert
      expect(decoded.map(v => v.content)).toEqual(versions.map(v => v.content));
      // 非内容字段也应保留
      expect(decoded.map(v => v.id)).toEqual(['v1', 'v2', 'v3']);
      expect(decoded.map(v => v.version)).toEqual([1, 2, 3]);
    });

    it('空版本列表：encodeVersionsToDeltas([]) 返回 []', () => {
      // Arrange & Act
      const result = encodeVersionsToDeltas([]);

      // Assert
      expect(result).toEqual([]);
    });

    it('空版本列表：decodeDeltasToVersions([]) 返回 []', () => {
      // Arrange & Act
      const result = decodeDeltasToVersions([]);

      // Assert
      expect(result).toEqual([]);
    });

    it('单版本：只含 1 个 Version 时编码解码正确', () => {
      // Arrange
      const versions: ChapterVersion[] = [makeVersion('v1', 'Only one version', 1)];

      // Act
      const stored = encodeVersionsToDeltas(versions);
      const decoded = decodeDeltasToVersions(stored);

      // Assert：首个版本为 full（delta=null）
      expect(stored).toHaveLength(1);
      expect(stored[0].delta).toBeNull();
      expect(decoded).toHaveLength(1);
      expect(decoded[0].content).toBe('Only one version');
      expect(decoded[0].id).toBe('v1');
    });
  });

  describe('特殊字符与 HTML', () => {
    it('content 含 Unicode（中文、emoji、\\u0001 边界字符）编码解码正确', () => {
      // Arrange：\u0001 在新格式 JSON 下被自动转义，不会破坏 delta 结构
      const specialContent = '你好世界😀\u0001边界字符';
      const versions: ChapterVersion[] = [
        makeVersion('v1', '初始内容', 1),
        makeVersion('v2', specialContent, 2),
      ];

      // Act
      const stored = encodeVersionsToDeltas(versions);
      const decoded = decodeDeltasToVersions(stored);

      // Assert
      expect(decoded[1].content).toBe(specialContent);
    });

    it('content 含中文与 emoji 多版本编码解码', () => {
      // Arrange
      const versions: ChapterVersion[] = [
        makeVersion('v1', '第一版本内容', 1),
        makeVersion('v2', '第二版本内容😀😁', 2),
        makeVersion('v3', '第三版本🎉🎊中文混合', 3),
      ];

      // Act
      const stored = encodeVersionsToDeltas(versions);
      const decoded = decodeDeltasToVersions(stored);

      // Assert
      expect(decoded.map(v => v.content)).toEqual(versions.map(v => v.content));
    });

    it('content 含 HTML 标签：delta 计算不破坏 HTML 结构', () => {
      // Arrange
      const versions: ChapterVersion[] = [
        makeVersion('v1', '<p>第一段</p><p>第二段</p>', 1),
        makeVersion('v2', '<p>第一段</p><p>修改后的第二段</p><strong>加粗</strong>', 2),
      ];

      // Act
      const stored = encodeVersionsToDeltas(versions);
      const decoded = decodeDeltasToVersions(stored);

      // Assert：HTML 标签应完整保留
      expect(decoded[1].content).toBe(versions[1].content);
    });
  });

  describe('增量 delta 结构', () => {
    it('第一个 delta 是 full（delta=null），后续是 diff（JSON 字符串）', () => {
      // Arrange
      const versions: ChapterVersion[] = [
        makeVersion('v1', 'base content', 1),
        makeVersion('v2', 'base content modified', 2),
        makeVersion('v3', 'base content modified again', 3),
      ];

      // Act
      const stored = encodeVersionsToDeltas(versions);

      // Assert：首个为 full（delta=null），后续为 diff（JSON 字符串，以 '{' 开头）
      // 注：实现未导出 isFullDelta / isDiffDelta 类型守卫，直接验证 delta 字段
      expect(stored[0].delta).toBeNull();
      expect(typeof stored[1].delta).toBe('string');
      expect(stored[1].delta!.startsWith('{')).toBe(true);
      expect(typeof stored[2].delta).toBe('string');
      expect(stored[2].delta!.startsWith('{')).toBe(true);
      // diff 版本的 content 字段被清空（仅存 delta）
      expect(stored[1].content).toBe('');
      expect(stored[2].content).toBe('');
    });

    it('解码后的 ChapterVersion 不含 delta 字段', () => {
      // Arrange
      const versions: ChapterVersion[] = [
        makeVersion('v1', 'content', 1),
        makeVersion('v2', 'content v2', 2),
      ];

      // Act
      const stored = encodeVersionsToDeltas(versions);
      const decoded = decodeDeltasToVersions(stored);

      // Assert：decoded 元素不应有 delta 属性
      expect(decoded[0]).not.toHaveProperty('delta');
      expect(decoded[1]).not.toHaveProperty('delta');
    });
  });

  describe('损坏容错', () => {
    it('损坏的旧格式 delta（aMid 含 \\u0001）应跳过并保留前一版本内容', () => {
      // Arrange：构造旧格式 delta，aMid 含 \u0001 导致 split 产生 >3 个 part
      // 旧格式：<prefixLen>\u0000<aMid>\u0001<bMid>\u0001<suffixLen>
      // 当 aMid 含 \u0001 时 parts.length !== 3，触发 "expected 3 parts" 错误
      const corruptedDelta = '0\u0000hel\u0001lo\u0001world\u00015';
      const stored: StoredVersion[] = [
        makeStored('v1', '基线内容', null, 1),
        makeStored('v2', '', corruptedDelta, 2),
      ];

      // Act：不应抛错
      const decoded = decodeDeltasToVersions(stored);

      // Assert：v2 降级为前一版本内容
      expect(decoded).toHaveLength(2);
      expect(decoded[0].content).toBe('基线内容');
      expect(decoded[1].content).toBe('基线内容');
    });

    it('损坏的 JSON delta 应跳过并保留前一版本内容', () => {
      // Arrange：JSON 格式但无法 parse
      const stored: StoredVersion[] = [
        makeStored('v1', '原始内容', null, 1),
        makeStored('v2', '', '{invalid json', 2),
      ];

      // Act
      const decoded = decodeDeltasToVersions(stored);

      // Assert
      expect(decoded[1].content).toBe('原始内容');
    });

    it('损坏 delta 后续的 full 版本可正常恢复', () => {
      // Arrange：v2 delta 损坏，v3 为 full（delta=null）
      const corruptedDelta = '0\u0000a\u0001b\u0001c\u00015';
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', corruptedDelta, 2),
        makeStored('v3', '第三版完整内容', null, 3),
      ];

      // Act
      const decoded = decodeDeltasToVersions(stored);

      // Assert：损坏 delta 不影响后续 full 版本
      expect(decoded[0].content).toBe('基线');
      expect(decoded[1].content).toBe('基线'); // 降级
      expect(decoded[2].content).toBe('第三版完整内容'); // full 正常
    });
  });

  describe('非数组输入', () => {
    it('decodeDeltasToVersions(null) 应抛 TypeError', () => {
      // Arrange & Act & Assert：stored.length 在 null 上访问抛 TypeError
      // 用 as unknown as 绕过 TS 类型检查，验证运行时行为
      expect(() => decodeDeltasToVersions(null as unknown as ReturnType<typeof encodeVersionsToDeltas>)).toThrow(TypeError);
    });

    it('decodeDeltasToVersions(undefined) 应抛 TypeError', () => {
      // Arrange & Act & Assert
      expect(() => decodeDeltasToVersions(undefined as unknown as ReturnType<typeof encodeVersionsToDeltas>)).toThrow(TypeError);
    });
  });

  describe('content 完全相同的连续版本', () => {
    it('delta 应为空字符串 no-op', () => {
      // Arrange
      const versions: ChapterVersion[] = [
        makeVersion('v1', 'same content', 1),
        makeVersion('v2', 'same content', 2),
        makeVersion('v3', 'same content', 3),
      ];

      // Act
      const stored = encodeVersionsToDeltas(versions);

      // Assert：后续 delta 为空字符串（computeSimpleDiff 在 a===b 时返回 ''）
      expect(stored[1].delta).toBe('');
      expect(stored[2].delta).toBe('');

      // 解码后内容一致
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded.map(v => v.content)).toEqual([
        'same content',
        'same content',
        'same content',
      ]);
    });
  });

  // ============ 旧格式 delta 向后兼容 ============
  describe('旧格式 delta 向后兼容', () => {
    it('有效的旧格式 delta 应正确解析', () => {
      // Arrange：旧格式 <prefixLen>\u0000<aMid>\u0001<bMid>\u0001<suffixLen>
      // 基线 'Hello World'，新版 'Hello JS World'：
      //   prefixLen=6 ('Hello '), suffixLen=6 (' World'), aMid='Java', bMid='JS'... 实际计算
      //   手算：prefix 'Hello ' (6), suffix ' World' (6), aMid='' (原 mid 'Java' 没了), bMid='JS '
      //   简化：用 prefix=5, suffix=5, aMid='X', bMid='Y' 构造
      //   base='abcdeABCDE' (10), prefix=5 ('abcde'), suffix=5 ('ABCDE'), aMid='', bMid='XYZ'
      //   新内容 = 'abcde' + 'XYZ' + 'ABCDE' = 'abcdeXYZABCDE'
      const oldDelta = '5\u0000\u0001XYZ\u00015';
      const stored: StoredVersion[] = [
        makeStored('v1', 'abcdeABCDE', null, 1),
        makeStored('v2', '', oldDelta, 2),
      ];

      // Act
      const decoded = decodeDeltasToVersions(stored);

      // Assert
      expect(decoded[1].content).toBe('abcdeXYZABCDE');
    });

    it('旧格式 delta 缺失 SEP_MID 抛错 → 降级到 prevContent', () => {
      // Arrange：delta 不含 \u0000
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', '5\u00015', 2), // 缺 SEP_MID
      ];

      // Act
      const decoded = decodeDeltasToVersions(stored);

      // Assert：降级到 prevContent
      expect(decoded[1].content).toBe('基线');
    });

    it('旧格式 delta prefixLen 非数字 → 降级', () => {
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', 'NaN\u0000\u0001X\u00010', 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });

    it('旧格式 delta suffixLen 非数字 → 降级', () => {
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', '0\u0000\u0001X\u0001NaN', 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });

    it('旧格式 delta prefixLen+suffixLen > base.length → 降级', () => {
      // base 长度 5，但 prefixLen=10 + suffixLen=10 = 20 > 5
      const stored: StoredVersion[] = [
        makeStored('v1', 'short', null, 1),
        makeStored('v2', '', '10\u0000\u0001X\u000110', 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('short');
    });
  });

  // ============ 新格式 delta 错误分支 ============
  describe('新格式 delta 错误分支', () => {
    it('prefixLen 非整数 → 降级', () => {
      // p=1.5 不是整数
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', JSON.stringify({ p: 1.5, a: '', b: 'X', s: 0 }), 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });

    it('prefixLen 为负 → 降级', () => {
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', JSON.stringify({ p: -1, a: '', b: 'X', s: 0 }), 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });

    it('suffixLen 非整数 → 降级', () => {
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', JSON.stringify({ p: 0, a: '', b: 'X', s: 'abc' }), 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });

    it('suffixLen 为负 → 降级', () => {
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', JSON.stringify({ p: 0, a: '', b: 'X', s: -5 }), 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });

    it('a 字段非字符串 → 降级', () => {
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', JSON.stringify({ p: 0, a: 123, b: 'X', s: 0 }), 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });

    it('b 字段非字符串 → 降级', () => {
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', JSON.stringify({ p: 0, a: '', b: null, s: 0 }), 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });

    it('prefixLen+suffixLen > base.length → 降级', () => {
      // base 长度 5，p=10 s=10 总和 20 > 5
      const stored: StoredVersion[] = [
        makeStored('v1', 'short', null, 1),
        makeStored('v2', '', JSON.stringify({ p: 10, a: '', b: 'X', s: 10 }), 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('short');
    });

    it('JSON parse 失败 → 降级', () => {
      const stored: StoredVersion[] = [
        makeStored('v1', '基线', null, 1),
        makeStored('v2', '', '{not valid json', 2),
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[1].content).toBe('基线');
    });
  });

  // ============ delta=undefined 兼容 ============
  describe('delta=undefined 兼容', () => {
    it('delta 为 undefined 时按完整内容处理', () => {
      // 旧文件可能没有 delta 字段，按 undefined 处理
      const stored: StoredVersion[] = [
        makeStored('v1', '完整内容1', null, 1),
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        { ...makeStored('v2', '完整内容2', null, 2), delta: undefined as any },
      ];
      const decoded = decodeDeltasToVersions(stored);
      expect(decoded[0].content).toBe('完整内容1');
      expect(decoded[1].content).toBe('完整内容2');
    });
  });

  // ============ 多版本链式重建 ============
  describe('多版本链式重建', () => {
    it('5 个版本连续修改，链式重建结果与原始一致', () => {
      const versions: ChapterVersion[] = [
        makeVersion('v1', 'AAAAAAAAAA', 1),
        makeVersion('v2', 'AAAABBBBBB', 2),
        makeVersion('v3', 'AAAABBBBBBCCCCC', 3),
        makeVersion('v4', 'AAAABBBBBB', 4), // 删除 CCCCC
        makeVersion('v5', 'XXXXXXXXXX', 5), // 完全替换
      ];

      const stored = encodeVersionsToDeltas(versions);
      const decoded = decodeDeltasToVersions(stored);

      expect(decoded.map(v => v.content)).toEqual(versions.map(v => v.content));
      // 首个 delta=null，其余为 JSON 字符串
      expect(stored[0].delta).toBeNull();
      for (let i = 1; i < stored.length; i++) {
        expect(stored[i].delta!.startsWith('{')).toBe(true);
      }
    });
  });
});
