import type { ChapterVersion } from '@/types';

/**
 * 版本历史增量 Diff 存储工具
 *
 * 背景：每个版本快照原本都存完整内容，长篇作品多版本后数据体积快速膨胀。
 * 方案：首个版本保留完整内容作为基线，后续版本仅存与前一版本的 diff；
 *      读取时按链式重建出每个版本的完整内容。
 *
 * 公共 API：
 *   - encodeVersionsToDeltas(versions) 将内存中的完整版本序列压缩为存储形式
 *   - decodeDeltasToVersions(stored)   将存储形式重建为完整版本序列
 *
 * diff 格式（字符串）：
 *   `<prefixLen>\u0000<aMid>\u0001<bMid>\u0001<suffixLen>`
 *   - prefixLen: 公共前缀长度
 *   - aMid:      旧版本中间被替换的片段
 *   - bMid:      新版本中间替换后的片段
 *   - suffixLen: 公共后缀长度
 *   完全相同时存空字符串以避免重复内容。
 *
 * 兼容性：delta 字段为 null/undefined 时按"完整内容"处理，旧文件可直接读取。
 */

// 控制字符：作为 delta 各字段的分隔符。章节正文（HTML）理论上极少包含它们，
// 但不能假设绝对不会出现，因此对 aMid/bMid 中的分隔符做转义。
const SEP_MID = '\u0000';
const SEP_PART = '\u0001';

// 转义 aMid/bMid 中的分隔符（SQL 风格加倍：\u0000 → \u0000\u0000，\u0001 → \u0001\u0001）
const escapeMid = (s: string): string =>
  s.replace(/\u0000/g, '\u0000\u0000').replace(/\u0001/g, '\u0001\u0001');

// 还原转义后的中间片段
const unescapeMid = (s: string): string =>
  s.replace(/\u0001\u0001/g, '\u0001').replace(/\u0000\u0000/g, '\u0000');

// 在尊重加倍转义的前提下按 delimiter 分割：
// delimiter 连续出现两次视为字面量（合并为一个），出现一次视为字段边界。
function splitRespectingEscape(s: string, delimiter: string): string[] {
  const parts: string[] = [];
  let current = '';
  let i = 0;
  while (i < s.length) {
    if (s[i] === delimiter) {
      if (s[i + 1] === delimiter) {
        current += delimiter; // 转义的字面量分隔符
        i += 2;
      } else {
        parts.push(current);
        current = '';
        i += 1;
      }
    } else {
      current += s[i];
      i += 1;
    }
  }
  parts.push(current);
  return parts;
}

export interface StoredVersion {
  id: string;
  chapterId: string;
  version: number;
  content: string;
  // null/undefined => content 为完整内容（基线或旧文件兼容）
  // string         => content 为空，需用 delta 与前一版本重建
  delta: string | null;
  wordCount: number;
  snapshotTime: string;
  description?: string;
  autoGenerated: boolean;
}

// 计算两段文本的 diff：前缀/后缀保留，中间替换段单独存储
function computeSimpleDiff(a: string, b: string): string {
  if (a === b) return ''; // 完全相同，无需任何替换
  const minLen = Math.min(a.length, b.length);
  let prefixLen = 0;
  while (prefixLen < minLen && a[prefixLen] === b[prefixLen]) prefixLen++;
  let suffixLen = 0;
  while (suffixLen < minLen - prefixLen && a[a.length - 1 - suffixLen] === b[b.length - 1 - suffixLen]) suffixLen++;
  const aMid = a.slice(prefixLen, a.length - suffixLen);
  const bMid = b.slice(prefixLen, b.length - suffixLen);
  // 转义中间片段中的分隔符，防止内容里的 \u0000/\u0001 破坏 delta 结构
  return `${prefixLen}${SEP_MID}${escapeMid(aMid)}${SEP_PART}${escapeMid(bMid)}${SEP_PART}${suffixLen}`;
}

// 将 diff 应用到基线，重建出新版本内容。delta 损坏时抛错而非静默回退，避免产生错误内容。
function applySimpleDiff(base: string, delta: string): string {
  if (delta === '') return base;
  // prefixLen 为纯数字，不会含 SEP_MID，因此第一个 SEP_MID 即 prefixLen 与 aMid 的边界
  const sepMidIdx = delta.indexOf(SEP_MID);
  if (sepMidIdx < 0) {
    throw new Error('Invalid delta: missing SEP_MID boundary');
  }
  const prefixLen = parseInt(delta.slice(0, sepMidIdx), 10);
  if (Number.isNaN(prefixLen) || prefixLen < 0) {
    throw new Error('Invalid delta: invalid prefix length');
  }
  // 在尊重转义的前提下按 SEP_PART 拆分为 [aMid, bMid, suffixLen]
  const parts = splitRespectingEscape(delta.slice(sepMidIdx + 1), SEP_PART);
  if (parts.length !== 3) {
    throw new Error('Invalid delta: expected 3 parts after SEP_MID');
  }
  // parts[0] 为旧内容被替换片段（重建不需要），parts[1] 为新内容片段
  const bMid = unescapeMid(parts[1]);
  const suffixLen = parseInt(parts[2], 10);
  if (Number.isNaN(suffixLen) || suffixLen < 0) {
    throw new Error('Invalid delta: invalid suffix length');
  }
  if (prefixLen + suffixLen > base.length) {
    throw new Error('Invalid delta: length out of range for base');
  }
  return base.slice(0, prefixLen) + bMid + base.slice(base.length - suffixLen);
}

export function encodeVersionsToDeltas(versions: ChapterVersion[]): StoredVersion[] {
  if (versions.length === 0) return [];
  const result: StoredVersion[] = [];
  let prevContent = '';
  for (let i = 0; i < versions.length; i++) {
    const v = versions[i];
    if (i === 0) {
      // 首个版本保留完整内容作为基线
      result.push({ ...v, delta: null });
    } else {
      // 后续版本仅存与前一版本的 diff，content 字段留空
      result.push({ ...v, content: '', delta: computeSimpleDiff(prevContent, v.content) });
    }
    prevContent = v.content;
  }
  return result;
}

export function decodeDeltasToVersions(stored: StoredVersion[]): ChapterVersion[] {
  if (stored.length === 0) return [];
  const result: ChapterVersion[] = [];
  let prevContent = '';
  for (const s of stored) {
    let content: string;
    if (s.delta === null || s.delta === undefined) {
      // 兼容旧文件：无 delta 字段时 content 即完整内容
      content = s.content;
    } else {
      content = applySimpleDiff(prevContent, s.delta);
    }
    // 重建出的 ChapterVersion 不带 delta 字段
    const { delta: _delta, ...rest } = s;
    result.push({ ...rest, content });
    prevContent = content;
  }
  return result;
}
